#apiVersion: v1
#kind: Secret
#metadata:
#  name: kongkwun-bot-secret
 # namespace: kongkwun-bot
#type: Opaque
#stringData:
 # LINE_CHANNEL_SECRET: "15c6f96efbd4b17fb920ffc8c91423ce"
  #LINE_CHANNEL_ACCESS_TOKEN: "h1Mn454ZsvgQzrDpwDFlLr6e3QJWf+dC8vUgjonWXD4ZqeG+qht76b0v/gihbsUcgTOkr72txjeNtieZ/vx5U60acg1zI7cjNQ7WqeURSmX5SmHq6uZwfpPIx4SeEI86S8ipRQYBn8RdYqUh5glUCQdB04t89/1O/w1cDnyilFU="
  #DATABASE_URL: "mysql://USER:PASSWORD@CLOUD_MYSQL_HOST:3306/kongkwun_bot"
